language: c

sudo: false

env:
  global:
    - LUAROCKS=3.0.3
  matrix:
    - LUA=lua5.2

branches:
  except:
    - slave
    - /^release-.*$/

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted

script:
  - modman deploy-all
  - busted